metadata.format.version = "1.1"

[versions]

velocity = "3.2.0-SNAPSHOT"
paper = "1.19.3-R0.1-SNAPSHOT"
krypton = "0.66.3"

runtask = "2.0.1"
pluginyml = "0.5.3"
userdev = "1.5.1"
blossom = "1.3.1"

adventure = "4.12.0"
brigadier = "1.0.18"


[libraries]

velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
krypton-server = { group = "org.kryptonmc", name = "krypton-server", version.ref = "krypton" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimesssage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

brigadier = { group = "com.mojang", name = "brigadier", version.ref = "brigadier" }

krypton-annotation = { group = "org.kryptonmc", name = "annotation-processor", version.ref = "krypton" }

[plugins]

pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
